go-spatial/geom

encoding/error.go
encoding/geojson/geojson.go
encoding/geojson/geojson_test.go

An initial pass at GeoJSON parser. There are few changes that needed to be made because they were solutions for writing only. The `Type` field in the Feature struct for example needs to be of type `string` or alias `string`.

Geojson Parser

---

bbox.go
spherical/extent.go

Creating a new spherical package makes clear that these functions operate on spherical coordinates rather than cartesian.

Move spherical functions  (Segment/Extent and Hull) to new package

---

bbox.go

The extentent was always initilizing the extent with [0,0,0,0]
instead of the first point in the geomentry and then calculating
the actual extent.

[bug fix] NewExtentFromGeometry incorrect ext

---

encoding/gpkg/binary_header.go
internal/debugger/constants.go
internal/debugger/create_recorder.go
internal/debugger/create_recorder_cgo.go
internal/debugger/debugger.go
internal/debugger/doc.go
internal/debugger/funcfileline.go
internal/debugger/record_test.go
internal/debugger/recorder.go
internal/debugger/recorder/funcfileline_test.go
internal/debugger/recorder/gpkg/gpkg.go
internal/debugger/recorder/recorder.go

Added a way to record what is going on inside the algorithims and visulize it in qGIS.

[debugger] Added the debugger

---

encoding/wkt/internal/token/token_test.go
encoding/wkt/wkt.go
encoding/wkt/wkt_test.go

updated wkt

---

encoding/mvt/README.md
encoding/mvt/mvt.go
encoding/mvt/prepare.go
encoding/mvt/prepare_internal_test.go

I removed `tegola.Tile` from the function signature. The encoding function now takes an `geom.Extent` that is used to represent the extent of a tile. It also takes the size of the ouput tile in pixels.
This approach makes it so the encoder does not have to worry about the `geom.Geometry`'s SRID. The passed in `geom.Extent` is expected to be in the same projection as the `geom.Geometry.
*Todo*: I need to add a comment in `PrepareGeo`, I'm not sure what happens when the geometry goes outside the tile. Are geometries allowed outside of the tile?

mvt: removing tegola artifacts and adding docs

---

bbox.go
internal/debugger/debugger.go
internal/debugger/recorder/gpkg/debug.go
internal/debugger/recorder/gpkg/gpkg.go
internal/debugger/recorder/recorder.go

Geom fixes

---

windingorder/debug.go
windingorder/windingorder.go
windingorder/windingorder_test.go

* ForPoints  handles colinear points. Returns Colinear for colinear
points.
* Added convenience function ForGeomPoints that will unwrap the geom.Point
into [2]float64 values
* Added new function Orientation that takes an yDirection value to return
the correct winding order for that direction of the y-axis

Updated windingorder

---

circle_test.go
cmp/cmp.go
cmp/cmp_test.go
geom.go
slippy/tile_test.go

* comparisons with zero are absoloute (epsilon method)
* comparisons with non-zeros are relative (bit pattern distance method)
I also renamed `TOLERANCE` to conform with Go conventions
performance difference (slower as expected)
```
name        old time/op    new time/op    delta
CmpFloat-4    4.89ms ± 1%    5.53ms ± 1%  +12.93%  (p=0.000 n=8+7)
name        old alloc/op   new alloc/op   delta
CmpFloat-4     66.7B ± 1%     75.1B ± 1%  +12.63%  (p=0.001 n=7+7)
name        old allocs/op  new allocs/op  delta
CmpFloat-4      0.00           0.00          ~     (all equal)
```

cmp: more accurate handling of large and small numbers

---

encoding/wkt/wkt_decode.go
encoding/wkt/wkt_decode_test.go
encoding/wkt/wkt_test.go
encoding/wkt/wkt_tile_test.go
testing/README.md
testing/ne_tiles.go

The changes in this pull request are actually part of #69 but I don't see that PR being merged soon (it's complicated and there's bigger fish to fry) but, I'd really like this patch so that tests can be compiled/run in a reasonable amount of time.
The only changes in this PR are build tags to the files which contain or organize tiles in the `testing` directory.

testing: added build tags to large test geometries

---

encoding/wkt/wkt.go
encoding/wkt/wkt_encode.go

for reference, here is the old code:
https://github.com/go-spatial/geom/blob/03aebece13f810618d1131f9cca3ceafaa76275c/encoding/wkt/wkt.go#L254-L300
and the new code:
https://github.com/go-spatial/geom/blob/f96bfa113903fc2fe3d4e824ce5985f4346bb736/encoding/wkt/wkt_encode.go#L582-L621

[wkt] Re added features from old encoding function

---

cmp/cmp.go
planar/coord/coord.go
planar/coord/coord_test.go
planar/coord/utm/errors.go
planar/coord/utm/utm.go
planar/coord/utm/utm_test.go

Initial conversion code that takes a LngLat value and transforms it into a UTM value.

UTM FromLngLat working

---

encoding/gpkg/binary_header.go
encoding/gpkg/binary_header_internal_test.go
encoding/gpkg/errors.go
encoding/gpkg/examples/points.go
encoding/gpkg/gpkg.go

Only gpkg needed the tags, usages of it are already being conditionally built

Made it so that you can build geom without cgo

---

cmp/empty.go
cmp/empty_test.go
encoding/wkt/wkt.go
encoding/wkt/wkt_decode.go
encoding/wkt/wkt_encode.go
encoding/wkt/wkt_test.go
encoding/wkt/wkt_tile_test.go

This would close #81, refer to that issue for more context.
* exposed various encoder options
* `Precision` for `strconv.FormatFloat`
* `Fmt` for `strconv.FormatFloat`, this wasn't talked about but I think it's be helpful 
* `Strict` see next bullet
* empy points never printed by decoder
* new strict decoding for stricter error checking
* moved some utility funcitons out of wkt into cmp
* imporoved performance and stability of encoder in removing whitespace
* I noticed this while running benchmarks on the decoder because it is called by `init` to decode a tile
There isn't much of a performance difference, most of the cpu time is spent in `encodeFloat` so
slight logic changes don't mean much.
**todo:** add tests to the `cmp` functions

[encoding] revisions to WKT encode

---

bbox.go
cmp/compare.go
cmp/empty.go
encoding/geojson/geojson.go
encoding/mvt/feature.go
encoding/wkb/internal/encode/encode.go
encoding/wkt/wkt_encode.go
geom.go
line.go
line_string.go
line_string_test.go
planar/clip/linestring.go
planar/simplify.go
set_geom.go

To apply this change (to any code base), one line of bash can be used:
```
sed  -e 's/\([Vv]\)erticies/\1ertices/g' -i '' $(grep -e '[Vv]erticies' -r . -l --exclude='./.git/*')
```
closes #44

Fix usage of the word "verticies" to "vertices"

---

planar/makevalid/makevalid_test.go
slippy/projections.go
slippy/projections_test.go
slippy/tile.go
slippy/tile_grid.go
slippy/tile_grid_test.go
slippy/tile_test.go

This will need to be used in concert w/ a PR (# to be updated) against `tegola` when I complete the conflicts from the current rebase against v0.11.x

Add tilegrid 4326

---

utils.go
utils_test.go

Added clone method to geom.Geometry and apply function

---

encoding/mvt/decode.go
encoding/mvt/decode_internal_test.go
encoding/mvt/feature.go
encoding/mvt/feature_test.go
polygon.go
testing/dynamic_geoms.go
testing/dynamic_geoms_test.go
winding/winding.go

* the mvt encoder now uses the YPositiveDown field of winding.Order
* added the mvt decoder
I added the decoder as a rider to this pr, but it can be removed if it should be merged somewhere else.

[mvt] fix encoder tests and added decoder

---

geom.go
point_test.go
pointm.go
pointm_test.go
pointms.go
pointms_test.go
points.go
points_test.go
pointz.go
pointz_test.go
pointzm.go
pointzm_test.go
pointzms.go
pointzms_test.go
pointzs.go
pointzs_test.go
set_geom.go

The following PR takes care of adding the support for the following Extended geometries for point type: `PointZ` (3D), `PointM` (2D+1D), `PointZM` (3D+1D), `PointS` (2D + SRID info), `PointZS` (3D + SRID info), `PointMS` (2D+1D + SRID info), `PointZMS` (3D+1D + SRID info). This is related to issue #16 . Still need to add support for all the other extended geometries (i.e. the same work needed for linestring, etc.).

Add extended geometry types for Point as expected by EWKB standard

---

geom.go
line_stringm.go
line_stringm_test.go
line_stringms.go
line_stringms_test.go
line_strings.go
line_strings_test.go
line_stringz.go
line_stringz_test.go
line_stringzm.go
line_stringzm_test.go
line_stringzms.go
line_stringzms_test.go
line_stringzs.go
line_stringzs_test.go
pointm.go
pointm_test.go
pointms.go
pointms_test.go
points.go
points_test.go
pointz.go
pointz_test.go
pointzm.go
pointzm_test.go
pointzms.go
pointzms_test.go
pointzs.go
pointzs_test.go
set_geom.go

As made for Point type, the PR contains the definitions of the extended geometries for LineString type.
Here basics methods for the new types have been defined, basically to reduce the extradimensions to 2D objectsin order to be integrated with the rest of the repo; e.g. LineStringZMS type is the most complete one, defining a linestring of 3+1D points in a given reference), and there's a method which reduces it to a LineStringZM which can be reduced as well to a simple LineString.

Add extended types for LineString

---

geom.go
multi_pointm.go
multi_pointm_test.go
multi_pointms.go
multi_pointms_test.go
multi_points.go
multi_points_test.go
multi_pointz.go
multi_pointz_test.go
multi_pointzm.go
multi_pointzm_test.go
multi_pointzms.go
multi_pointzms_test.go
multi_pointzs.go
multi_pointzs_test.go
set_geom.go

As made for Point and LineString types, the PR contains the definitions of the extended geometries for MultiPoint type.
As made for LineString, basics methods for the new types have been defined, basically to reduce the extradimensions to 2D objects in order to be integrated with the rest of the repo.

Add extended types for MultiPoint geometries

---

geom.go
line_stringms.go
line_strings.go
line_stringzms.go
line_stringzs.go
multi_line_stringm.go
multi_line_stringm_test.go
multi_line_stringms.go
multi_line_stringms_test.go
multi_line_strings.go
multi_line_strings_test.go
multi_line_stringz.go
multi_line_stringz_test.go
multi_line_stringzm.go
multi_line_stringzm_test.go
multi_line_stringzms.go
multi_line_stringzms_test.go
multi_line_stringzs.go
multi_line_stringzs_test.go
set_geom.go

The PR contains the definitions of the extended geometries for MultiLineString type. As made for the previous extended geometries, basics methods for the new types have been defined to reduce the extradimensions to 2D objects in order to be integrated with the rest of the repo.
**NOTE**: The PR contains also changes related to LineString geometries after having executed a `go fmt` command.

Add support for extended MultiLineString geometries

---

geom.go
line.go
polygon_test.go
polygonm.go
polygonm_test.go
polygonms.go
polygonms_test.go
polygons.go
polygons_test.go
polygonz.go
polygonz_test.go
polygonzm.go
polygonzm_test.go
polygonzms.go
polygonzms_test.go
polygonzs.go
polygonzs_test.go
set_geom.go

The PR contains the definitions of the extended geometries for `Polygon` type. As made for the previous extended geometries, basics methods for the new types have been defined to reduce the extradimensions to 2D objects in order to be integrated with the rest of the repo.
**NOTE**: Additional `Line` types have been defined to complain the `AsSegment` method of the extended Polygons in order to obtain segments of 3D, 2D+1D and 3D+1D points.

Add support for the extended Polygon geometries

---

README.md
encoding/error.go
encoding/geojson/geojson.go
encoding/geojson/geojson_test.go

The current way of using the `geojson` package requires one to wrap a geometry several times.
This PR introduces three new methods to simplify using the package.
1. `Marshal` -- which will take any geom.Geometry, or slice of geom.Geometries, or a `geojson.Feature`, or a `geojson.FeatureCollection` and return a `geojson` encoded version of it, or an error.
2. `MarshalIndent` is the same as Marshal, returning a pretty version of the output instead
3. `Unmarshal` which will take an encoded `geojson` byte slice, and return either a `geojson.Feature`, or a `geojson.FeatureCollection`.
* In addition to the above a few documentation updates, and general fixes.
@gbroccolo could you give this a review as well. Thank you.

Add a general Marshal and Unmarshal function to geojson package.

---

cmp/compare.go
cmp/empty.go
cmp/empty_test.go
encoding/gpkg/binary_header.go
encoding/gpkg/gpkg.go
geom.go
planar/makevalid/makevalid_test.go
planar/triangulate/delaunay/subdivision/geom.go

It was reported that one of our comparison functions was using math.NaN incorrectly. Turns out this comparison function was a duplicate of
another function that was doing the comparison correctly, and had tests. Removed the duplicate function, and references to it were ported to
the correct function.
fixes #115

[compare] Consolidated Comparison functions

---

slippy/tile.go

The `FromBounds` was returning `nil` rather than the list of tiles it generated. This PR fixes that.

Update tile.go to return `[]Tile` from in `FromBounds` method.

---

planar/coord/utm/utm.go

Fix for #119
The rounding to the desired precision depends on the application, so I believe it's better to leave it out of the UTM conversion.

Removed rounding of UTM coordinates

---

encoding/geojson/errros.go
encoding/geojson/geojson.go
encoding/geojson/geojson_test.go

When unmarshalling geojson the system was assuming that certain keys just existed; this cause
a panic when those keys did not exist.
Now the system will check for the existence of the key and return and error if the keys don't
exist.
* minor lint cleanup as well.
fixes #118

[#118] When unmarshalling geojson the system was not checking for keys
